# This file was generated by GoReleaser. DO NOT EDIT.
cask "roji" do
  version "1.0.7"

  on_macos do
    on_intel do
      sha256 "2ecb2c9d78d2fdd90dcc8d1bd886207dc34c028507ae4ad25bca2fd5133f2371"
      url "https://github.com/kan/roji/releases/download/v#{version}/roji_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "460756c4e3d9d75325feeece257fadd03550ee638b5d15b852b992169ff9791d"
      url "https://github.com/kan/roji/releases/download/v#{version}/roji_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d476231d2ddeb60e204d597c31fa5f1194afff4ab6d4da8e438cf237d5a5fed3"
      url "https://github.com/kan/roji/releases/download/v#{version}/roji_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "14ded36f6e87b1e08c3c30fc434279eb3d851f80f652f13c9cbd5eb0ae72be5a"
      url "https://github.com/kan/roji/releases/download/v#{version}/roji_Linux_arm64.tar.gz"
    end
  end

  name "roji"
  desc "A simple reverse proxy for local development. Auto-discovers Docker Compose services and provides HTTPS access via *.dev.localhost."
  homepage "https://github.com/kan/roji"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "roji"

  # No zap stanza required

  caveats <<~EOS
    After installation, run:
      sudo roji doctor --fix
      sudo roji ca install
      sudo roji service install && sudo roji service start
  EOS
end
