# This file was generated by GoReleaser. DO NOT EDIT.
cask "roji" do
  version "1.0.2"

  on_macos do
    on_intel do
      url "https://github.com/kan/roji/releases/download/v#{version}/roji_Darwin_x86_64.tar.gz"
      sha256 "7d30efeb7df17e67c286d2b2c00c06c27ed2be9f3d065bb2966fd0e5c4fbf84a"
    end
    on_arm do
      url "https://github.com/kan/roji/releases/download/v#{version}/roji_Darwin_arm64.tar.gz"
      sha256 "85bf4583a3942458206db7527b7a179f8d0a7b396aa899608097ba4dda6d7198"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kan/roji/releases/download/v#{version}/roji_Linux_x86_64.tar.gz"
      sha256 "82a41761f18a1b11df85626642fabead2e9c01e982f7297bf21cd573ba9f425d"
    end
    on_arm do
      url "https://github.com/kan/roji/releases/download/v#{version}/roji_Linux_arm64.tar.gz"
      sha256 "9063618a63d24c70ab3bd8b0c2305b60dc5511ffa049e9067c96eb088a154185"
    end
  end

  name "roji"
  desc "A simple reverse proxy for local development. Auto-discovers Docker Compose services and provides HTTPS access via *.dev.localhost."
  homepage "https://github.com/kan/roji"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "roji"

  # No zap stanza required

  caveats <<~EOS
    After installation, run:
      sudo roji doctor --fix
      sudo roji ca install
      sudo roji service install && sudo roji service start
  EOS
end
