# This file was generated by GoReleaser. DO NOT EDIT.
cask "roji" do
  name "roji"
  desc "A simple reverse proxy for local development. Auto-discovers Docker Compose services and provides HTTPS access via *.dev.localhost."
  homepage "https://github.com/kan/roji"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "roji"

  on_macos do
    on_intel do
      url "https://github.com/kan/roji/releases/download/v#{version}/roji_Darwin_x86_64.tar.gz"
      sha256 "4a80ec11da7b77d916849a29108c0b8d903c991431e12da2450620e263b5f878"
    end
    on_arm do
      url "https://github.com/kan/roji/releases/download/v#{version}/roji_Darwin_arm64.tar.gz"
      sha256 "ca0af2e96454576739f9c8229ab65fa0784819dfa664392191df2d102cbce4e6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kan/roji/releases/download/v#{version}/roji_Linux_x86_64.tar.gz"
      sha256 "1de976a44bb600f644380be1573b9f24fdedf28517170088366fa5fe6720a464"
    end
    on_arm do
      url "https://github.com/kan/roji/releases/download/v#{version}/roji_Linux_arm64.tar.gz"
      sha256 "f02099b4680118c136d77ddc490dc43d2b09d36065afd7f0fd60245db21117c1"
    end
  end

  caveats do
    "After installation, run:"
    "  sudo roji doctor --fix"
    "  sudo roji ca install"
    "  sudo roji service install && sudo roji service start"
  end

  # No zap stanza required
end
